{{- if not .Values.session.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polaris-console.secretName" . }}
  labels:
    {{- include "polaris-console.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.session.secretKey }}: {{ include "polaris-console.sessionSecret" . | quote }}
{{- end }}
