replicaCount: 1

config:
  cookieSecure: false
  allowedOrigins:
    - http://localhost:8000
  allowAnyTargetHost: true

networkPolicy:
  enabled: false

security:
  requireCookieSecure: false
  requireNetworkPolicy: false
  disallowOpenEgress: false
