apiVersion: v1
entries:
  polaris-console:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: 0.1.0
    created: "2026-05-20T05:50:14.583288898Z"
    description: Dynamic Apache Polaris web console with a hardened FastAPI backend.
    digest: a31cacc10dfc8b4a4e2ebd667ade9ea9bd170de1c6fddfbc239df1ec89d487c8
    home: https://github.com/tsukubatexas/polaris-console
    keywords:
    - apache-polaris
    - iceberg
    - catalog
    - data-platform
    maintainers:
    - name: tsukubatexas
      url: https://github.com/tsukubatexas
    name: polaris-console
    sources:
    - https://github.com/tsukubatexas/polaris-console
    type: application
    urls:
    - https://raw.githubusercontent.com/tsukubatexas/polaris-console/gh-pages/charts/polaris-console-0.1.0.tgz
    version: 0.1.0
generated: "2026-05-20T05:50:14.582181908Z"
